/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.nanite.mlp;

import java.io.File;
import java.io.IOException;
import java.io.Writer;
import java.io.FileWriter;
import java.nio.file.Files;
import java.nio.file.Path;

import org.gradle.testkit.runner.GradleRunner;
import org.gradle.testkit.runner.BuildResult;
import org.gradle.testkit.runner.TaskOutcome;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple functional test for the 'dev.nanite.mlp.greeting' plugin.
 */
public class MultiLoaderPluginFunctionalTest {
    @Test public void canRunTask() throws IOException {
        // Setup the test build

        // Run the build
        GradleRunner runner = GradleRunner.create();
        runner.forwardOutput();
        runner.withPluginClasspath();
        runner.withProjectDir(new File("test"));
        BuildResult result = runner.build();
        result.task("at2t");
        // Verify the result
//        assertTrue(result.getOutput().contains("Hello from plugin 'dev.nanite.mlp.greeting'"));
    }

    private void writeString(File file, String string) throws IOException {
        try (Writer writer = new FileWriter(file)) {
            writer.write(string);
        }
    }
}
