/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.imabad.mlp;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple unit test for the 'dev.imabad.mlp.greeting' plugin.
 */
public class MultiLoaderPluginTest {
//    @Test public void pluginRegistersATask() {
//        // Create a test project and apply the plugin
//        Project project = ProjectBuilder.builder().build();
//        project.getPlugins().apply("dev.imabad.mlp.greeting");
//
//        // Verify the result
//        assertNotNull(project.getTasks().findByName("greeting"));
//    }
}
