# Kindly borrowed from modmuss50/mod-publish-plugin
name: Publish
on: [workflow_dispatch] # Manual trigger

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-22.04
    environment: Production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Fix borked permissions
        run: chmod +x ./gradlew
      - name: Publish
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
          NANITE_TOKEN: ${{ secrets.NANITE_DEPLOY }}
        run: ./gradlew publish publishPlugins